# Generated by Django 4.2.6 on 2023-10-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='period',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='периодичность'),
        ),
    ]
