# Generated by Django 4.2.6 on 2023-10-23 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='is_published',
            new_name='is_public',
        ),
    ]
